name: invoice-manager

informers:
  - name: slack-service-monitoring-errors
    type: slack
    config:
      webhookUrl: https://hooks.slack.com/services/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

backends:
  - name: invoice-manager-dev
    url: http://localhost:1234/healthy
    callEachSec: 5
    response:
      expectCode: 200
      onFail:
        inform:
          - informer: slack-service-monitoring-errors

  # Using basic auth
  # - name: invoice-manager-dev
  #   url: http://localhost:1234/healthy
  #   auth:
  #     username: "user"
  #     password: "password"
  #   callEachSec: 5
  #   response:
  #     expectCode: 200
  #     onFail:
  #       inform:
  #         - informer: slack-service-monitoring-errors
