name: invoice-manager 

informers:
  - name: slack-iceberg-invoice-manager-errors
    type: slack
    config:
       webhookUrl: https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX

backends:
  - name: 
    url: https://invoice-manager.xtk-dev.de/health
    response: 
      expectCode: 200
      onFail:
        inform:
          - informer: slack-iceberg-invoice-manager-errors
            template: "Error service invoice-manager component '{{name}}'"

