name: invoice-manager

informers:
  - name: slack-service-monitoring-errors
    type: slack
    config:
      # Note: use a real slack webhook here (This is just a template)
      webhookUrl: https://hooks.slack.com/services/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

backends:
  # Can be started with 'Make backendMock'
  - name: invoice-manager-dev
    url: http://localhost:1234/healthy
    callEachSec: 10
    response:
      expectCode: 200
      onFail:
        inform:
          - informer: slack-service-monitoring-errors

  # Using basic auth
  # - name: invoice-manager-dev
  #   url: http://localhost:1234/healthy
  #   auth:
  #     username: "user"
  #     password: "password"
  #   callEachSec: 5
  #   response:
  #     expectCode: 200
  #     onFail:
  #       inform:
  #         - informer: slack-service-monitoring-errors
